In [1]:
import pandas as pd
import requests
import numpy as np

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [2]:
df.rename(columns={'entity': "Pais",  'code': "Código", 'year': "Año" ,'life_expectancy_0': "Esperanza de Vida"}, inplace=True)

In [3]:
df.head(3)

          Pais Código   Año  Esperanza de Vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138

In [4]:
df.reset_index(inplace=True)

In [5]:
df.reset_index(inplace=True)
df.set_index(["Pais", "Año"], inplace = True)

In [6]:
df.loc[df.index.get_level_values('Pais').str.contains("U", case = False, regex = True)]

                        level_0  index Código  Esperanza de Vida
Pais              Año
Anguilla          1950      604    604    AIA            55.0563
                  1951      605    605    AIA            55.5932
                  1952      606    606    AIA            56.0813
                  1953      607    607    AIA            56.5817
                  1954      608    608    AIA            57.0804
...                         ...    ...    ...                ...
Wallis and Futuna 2019    21183  21183    WLF            77.9936
                  2020    21184  21184    WLF            78.1637
                  2021    21185  21185    WLF            77.4609
                  2022    21186  21186    WLF            78.5005
                  2023    21187  21187    WLF            78.6286

[7375 rows x 4 columns]

In [7]:
df.loc[df["Código"].isnull()]

                                            level_0  index Código  \
Pais                                  Año
Americas                              1770      375    375    NaN
                                      1830      376    376    NaN
                                      1850      377    377    NaN
                                      1870      378    378    NaN
                                      1900      379    379    NaN
...                                             ...    ...    ...
Small Island Developing States (SIDS) 2019    17703  17703    NaN
                                      2020    17704  17704    NaN
                                      2021    17705  17705    NaN
                                      2022    17706  17706    NaN
                                      2023    17707  17707    NaN

                                            Esperanza de Vida
Pais                                  Año
Americas                              1770            34.8000
                                      1830            34.8000
                                      1850            35.1000
                                      1870            35.1000
                                      1900            41.0000
...                                                       ...
Small Island Developing States (SIDS) 2019            72.0847
                                      2020            71.7761
                                      2021            69.8938
                                      2022            72.1257
                                      2023            72.7255

[1348 rows x 4 columns]

In [8]:
df.dropna(subset=["Código"], inplace=True)
df.isnull().sum()

level_0              0
index                0
Código               0
Esperanza de Vida    0
dtype: int64

In [9]:
resultado = (
    df.groupby("Pais")["Esperanza de Vida"].mean().sort_values(ascending=True)
)

resultado2020 = (
    df.loc[df.index.get_level_values("Año") == 2020]
    .groupby("Pais")["Esperanza de Vida"]
    .mean()
    .sort_values(ascending=True)
)

resultado2020.head(10)

Pais
Central African Republic    50.5959
Nigeria                     53.0724
Chad                        53.0818
Lesotho                     55.1325
Somalia                     57.0948
South Sudan                 57.6479
Mali                        58.8577
Guinea                      59.3499
Sierra Leone                59.6935
Eswatini                    59.8618
Name: Esperanza de Vida, dtype: float64